config/routes.rb
Rails.application.routes.draw do
  
  get 'airs/index'
  
  devise_for :users

  
  resources :airs
  
  root 'airs#index'

end

app/models/air.rb
class Air < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :airs
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "profile.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => [:login]
         
  attr_accessor :login
  
   def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
  
  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  } 
  
  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
  
end

app/controllers/airs_controller.rb
class AirsController < ApplicationController
  before_action :set_air, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!


  # GET /airs
  # GET /airs.json
  def index
    @airs = Air.all
  end

  # GET /airs/1
  # GET /airs/1.json
  def show
  end

  # GET /airs/new
  def new
    @air = Air.new
  end

  # GET /airs/1/edit
  def edit
  end

  # POST /airs
  # POST /airs.json
  def create
    @air = Air.new(air_params)
    @air.room_id = current_user.id
    respond_to do |format|
      if @air.save
        format.html { redirect_to @air, notice: 'Air was successfully created.' }
        format.json { render :show, status: :created, location: @air }
      else
        format.html { render :new }
        format.json { render json: @air.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airs/1
  # PATCH/PUT /airs/1.json
  def update
    respond_to do |format|
      if @air.update(air_params)
        format.html { redirect_to @air, notice: 'Air was successfully updated.' }
        format.json { render :show, status: :ok, location: @air }
      else
        format.html { render :edit }
        format.json { render json: @air.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airs/1
  # DELETE /airs/1.json
  def destroy
    @air.destroy
    respond_to do |format|
      format.html { redirect_to airs_url, notice: 'Air was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
    @user = User.create( user_params )
  end

  private
  
    def user_params
      params.require(:user).permit(:avatar)
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_air
      @air = Air.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def air_params
      params.require(:air).permit(:room_id, :room_type, :room_name, :location, :description, :accomodation, :bedrooms, :beds, :bathrooms, :price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
   def configure_permitted_parameters
    added_attrs = [:avatar , :username, :fullname, :email, :contactnumber, :about, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
end

app/helpers/airs_helper.rb
module AirsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airs/_form.html.erb
<%= form_for(@air) do |f| %>
  <% if @air.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@air.errors.count, "error") %> prohibited this air from being saved:</h2>

      <ul>
      <% @air.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.text_field :room_type %>
  </div>
  <div class="field">
    <%= f.label :room_name %><br>
    <%= f.text_field :room_name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :accomodation %><br>
    <%= f.number_field :accomodation %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.number_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :beds %><br>
    <%= f.number_field :beds %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %><br>
    <%= f.number_field :bathrooms %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airs/edit.html.erb
<h1>Editing Air</h1>

<%= render 'form' %>

<%= link_to 'Show', @air %> |
<%= link_to 'Back', airs_path %>

app/views/airs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Airs</h1>

<%= image_tag current_user.avatar(:thumb) %>

<table>
  <thead>
    <tr>
      <th>Room type</th>
      <th>Room name</th>
      <th>Location</th>
      <th>Description</th>
      <th>Accomodation</th>
      <th>Bedrooms</th>
      <th>Beds</th>
      <th>Bathrooms</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airs.each do |air| %>
      <tr>
        <td><%= air.room_id %></td>
        <td><%= air.room_type %></td>
        <td><%= air.room_name %></td>
        <td><%= air.location %></td>
        <td><%= air.description %></td>
        <td><%= air.accomodation %></td>
        <td><%= air.bedrooms %></td>
        <td><%= air.beds %></td>
        <td><%= air.bathrooms %></td>
        <td><%= air.price %></td>
        <td><%= link_to 'Show', air %></td>
        <td><%= link_to 'Edit', edit_air_path(air) %></td>
        <td><%= link_to 'Destroy', air, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Air', new_air_path %>

app/views/airs/new.html.erb
<h1>New Air</h1>

<%= render 'form' %>

<%= link_to 'Back', airs_path %>

app/views/airs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @air.room_id %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @air.room_type %>
</p>

<p>
  <strong>Room name:</strong>
  <%= @air.room_name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @air.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @air.description %>
</p>

<p>
  <strong>Accomodation:</strong>
  <%= @air.accomodation %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @air.bedrooms %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @air.beds %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @air.bathrooms %>
</p>

<p>
  <strong>Price:</strong>
  <%= @air.price %>
</p>

<%= link_to 'Edit', edit_air_path(@air) %> |
<%= link_to 'Back', airs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>airbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
           <li> <%= link_to 'Settings', edit_user_registration_path, :class => 'navbar-link' %></li>
           <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
         <% else %>
           <li>  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>  </li>
           <li>  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>  </li>
         <% end %>
<%= yield %>

</body>
</html>